services:
  - type: web
    name: simulacion-techclassuc
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python main.py --salida assets
    startCommand: python src/app.py
    autoDeploy: true
