services:
  - type: web
    name: simulacion-techclassuc
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python main.py --salida assets
    startCommand: gunicorn src.app:app
    autoDeploy: true
